/**
 * The performance benchmark (spec §17.5): `npm run bench` builds the game, then in Chrome:
 *
 * - times a cold load to the title screen;
 * - runs 60 s through the heaviest case (a Corridor depot in a storm, two players wandering on scripted sticks,
 *   ALERT, every observer active), sampling every frame: the frame interval, its CPU time, draw calls,
 *   triangles, the active dynamic lights, and the JS heap;
 * - measures the gzipped bundle.
 *
 * Results go to qa/bench.md; it exits non-zero if a budget is broken.
 *   npx tsx tools/bench.ts [--seconds 60]
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { gzipSync } from 'node:zlib';
import type { BenchSamples } from '../src/qa';
import { startSession } from './browser';

const BUDGET = {
  frameP95: 16.7,
  calls: 150,
  triangles: 200_000,
  lights: 8,
  heapMb: 400,
  gzipMb: 2.5,
  loadSeconds: 5,
};

function pct(xs: number[], p: number): number {
  if (xs.length === 0) return NaN;
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.min(s.length - 1, Math.floor((p / 100) * s.length))];
}

function gzippedBundle(): { bytes: number; files: string[] } {
  const dir = 'dist/assets';
  let bytes = 0;
  const files: string[] = [];
  for (const f of readdirSync(dir)) {
    if (!/\.(js|css)$/.test(f)) continue;
    bytes += gzipSync(readFileSync(join(dir, f))).length;
    files.push(f);
  }
  const html = readFileSync('dist/index.html');
  bytes += gzipSync(html).length;
  return { bytes, files };
}

async function main(): Promise<void> {
  const argv = process.argv.slice(2);
  const seconds = argv.includes('--seconds') ? Number(argv[argv.indexOf('--seconds') + 1]) : 60;
  const bundle = gzippedBundle();
  const s = await startSession('preview');
  let load: number | undefined;
  let samples: BenchSamples | undefined;
  const errors: string[] = [];
  try {
    // Cold load to the title.
    {
      const { page, messages } = await s.newPage(1920, 1080);
      const t0 = Date.now();
      await page.goto(s.url + '?bench=1', { waitUntil: 'load' });
      await page.waitForFunction(
        () => window.__exodus?.ready() === true && window.__exodus.scene() === 'title',
        undefined,
        {
          timeout: 60_000,
        },
      );
      load = (Date.now() - t0) / 1000;
      errors.push(...messages);
      await page.context().close();
    }
    // The heaviest case, in real time.
    {
      const { page, messages } = await s.newPage(1920, 1080);
      await page.goto(s.url + '?bench=1&scene=depot&region=corridor&weather=storm&players=2&alert=1&seed=7', {
        waitUntil: 'load',
      });
      await page.waitForFunction(() => window.__exodus?.ready() === true, undefined, { timeout: 60_000 });
      await page.evaluate(() => window.__exodus!.benchStart(true));
      await page.waitForTimeout(seconds * 1000);
      samples = await page.evaluate(() => window.__exodus!.benchStop());
      errors.push(...messages);
      await page.context().close();
    }
  } finally {
    await s.close();
  }
  if (!samples || load === undefined) throw new Error('the benchmark did not finish');
  const sm = samples;
  // The first second settles (shader compiles, the first light assignments).
  const settle = Math.min(60, Math.floor(sm.intervalMs.length / 10));
  const cut = (xs: number[]): number[] => xs.slice(settle);
  const frameP95 = pct(cut(sm.intervalMs), 95);
  const cpuP95 = pct(cut(sm.cpuMs), 95);
  const calls = Math.max(...cut(sm.calls));
  const tris = Math.max(...cut(sm.triangles));
  const lights = Math.max(...cut(sm.lights));
  const heap = Math.max(...cut(sm.heapMb));
  const gzipMb = bundle.bytes / (1024 * 1024);
  const rows: [string, string, string, boolean][] = [
    [
      'Frame time (p95 frame interval)',
      `${frameP95.toFixed(1)} ms`,
      `≤ ${BUDGET.frameP95} ms`,
      frameP95 <= BUDGET.frameP95,
    ],
    ['CPU time per frame (p95, tick + render submit)', `${cpuP95.toFixed(1)} ms`, 'info', true],
    ['Draw calls (max)', `${calls}`, `≤ ${BUDGET.calls}`, calls <= BUDGET.calls],
    ['Triangles (max)', `${tris}`, `≤ ${BUDGET.triangles}`, tris <= BUDGET.triangles],
    ['Active dynamic lights (max)', `${lights}`, `≤ ${BUDGET.lights}`, lights <= BUDGET.lights],
    [
      'JS heap (max)',
      heap > 0 ? `${heap.toFixed(0)} MB` : 'n/a',
      `≤ ${BUDGET.heapMb} MB`,
      heap <= BUDGET.heapMb,
    ],
    ['Gzipped bundle', `${gzipMb.toFixed(2)} MB`, `≤ ${BUDGET.gzipMb} MB`, gzipMb <= BUDGET.gzipMb],
    [
      'Load to title (local preview server)',
      `${load.toFixed(1)} s`,
      `≤ ${BUDGET.loadSeconds} s`,
      load <= BUDGET.loadSeconds,
    ],
  ];
  const lines = [
    '# Performance benchmark',
    '',
    `Generated by \`npm run bench\` (spec §17.5): ${seconds} s through a Corridor depot in a storm, two players on scripted sticks, ALERT, every observer active; 1920×1080 in headless Chrome. ${sm.intervalMs.length} frames sampled (the first ${settle} skipped while shaders compile).`,
    '',
    '| Budget | Measured | Limit | |',
    '|---|---|---|---|',
    ...rows.map(
      ([k, v, lim, ok]) => `| ${k} | ${v} | ${lim} | ${lim === 'info' ? '' : ok ? 'pass' : 'FAIL'} |`,
    ),
    '',
    `Mean frame interval ${(cut(sm.intervalMs).reduce((a, b) => a + b, 0) / Math.max(1, cut(sm.intervalMs).length)).toFixed(2)} ms; mean CPU ${(cut(sm.cpuMs).reduce((a, b) => a + b, 0) / Math.max(1, cut(sm.cpuMs).length)).toFixed(2)} ms.`,
    `Bundle files: ${bundle.files.join(', ')}.`,
    '',
    errors.length
      ? `Console messages:\n\n\`\`\`\n${errors.join('\n')}\n\`\`\``
      : 'No console errors or warnings.',
    '',
  ];
  writeFileSync('qa/bench.md', lines.join('\n'));
  for (const [k, v, lim, ok] of rows)
    console.log(
      `${k.padEnd(48)} ${v.padStart(10)}  ${lim.padEnd(10)} ${lim === 'info' ? '' : ok ? 'pass' : 'FAIL'}`,
    );
  if (errors.length) console.log(`console: ${errors.length} messages`);
  console.log('qa/bench.md written');
  if (rows.some(([, , lim, ok]) => lim !== 'info' && !ok) || errors.length > 0) process.exitCode = 1;
}

void main();
